version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: carwash
      MYSQL_USER: carwashbd
      MYSQL_PASSWORD: carwashbd
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3307:3306"

# docker compose up -d para levantar la BD.